on: [push]

jobs:
  fingerprint:
    runs-on: ubuntu-latest
    name: check expo fingerprint
    steps:
      - uses: actions/checkout@v3

      - name: expo fingerprint
        uses: wwdrew/expo-fingerprint-action@v1.4
