on: [push]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read

jobs:
  fingerprint:
    runs-on: ubuntu-latest
    name: check expo fingerprint
    outputs:
      matches: ${{ steps.fingerprint.outputs.matches }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3

      - run: npm ci

      - name: expo fingerprint
        id: fingerprint
        uses: wwdrew/expo-fingerprint-action@v1.5

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          message: 'Adding expo fingerprint'

  build:
    runs-on: ubuntu-latest
    name: build expo project
    needs: fingerprint
    if: ${{ needs.fingerprint.outputs.matches == 'false' }}
    steps:
      - run: echo "NEED TO BUILD"

  update:
    runs-on: ubuntu-latest
    name: update expo project
    needs: fingerprint
    if: ${{ needs.fingerprint.outputs.matches == 'true' }}
    steps:
      - run: echo "NEED TO UPDATE"
