on: [push]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read

jobs:
  fingerprint:
    runs-on: ubuntu-latest
    name: check expo fingerprint
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3

      - run: npm ci

      - name: expo fingerprint
        uses: wwdrew/expo-fingerprint-action@v1.5

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          message: 'Adding expo fingerprint'

  build:
    runs-on: ubuntu-latest
    needs: fingerprint
    if: ${{ jobs.fingerprint.outputs.matches == 'false' }}
    steps:
      - name: We should build
        run: echo "Match was ${{ jobs.fingerprint.outputs.matches }}"

  update:
    runs-on: ubuntu-latest
    needs: fingerprint
    if: ${{ jobs.fingerprint.outputs.matches == 'true' }}
    steps:
      - name: We should build
        run: echo "Match was ${{ jobs.fingerprint.outputs.matches }}"
