on: [push]

jobs:
  fingerprint:
    runs-on: ubuntu-latest
    name: check expo fingerprint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - run: npm ci

      - name: expo fingerprint
        uses: wwdrew/expo-fingerprint-action@v1.5
